# Generated by Django 6.0.5 on 2026-05-24 23:57

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("source_type", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="RawDataPayload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_data", models.JSONField()),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Normalization"),
                            ("NEEDS_REVIEW", "Needs Analyst Review"),
                            ("APPROVED", "Approved for Audit"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ingestion.datasource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NormalizedEmissionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope_category",
                    models.CharField(
                        choices=[
                            ("SCOPE_1", "Scope 1 (Direct)"),
                            ("SCOPE_2", "Scope 2 (Indirect Electricity)"),
                            ("SCOPE_3", "Scope 3 (Value Chain)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("emission_source", models.CharField(max_length=100)),
                ("activity_date_start", models.DateField()),
                ("activity_date_end", models.DateField(blank=True, null=True)),
                ("normalized_value", models.FloatField()),
                ("normalized_unit", models.CharField(max_length=20)),
                ("ai_audit_note", models.TextField(blank=True, null=True)),
                (
                    "raw_payload",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="normalized_record",
                        to="ingestion.rawdatapayload",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalNormalizedEmissionRecord",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "scope_category",
                    models.CharField(
                        choices=[
                            ("SCOPE_1", "Scope 1 (Direct)"),
                            ("SCOPE_2", "Scope 2 (Indirect Electricity)"),
                            ("SCOPE_3", "Scope 3 (Value Chain)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("emission_source", models.CharField(max_length=100)),
                ("activity_date_start", models.DateField()),
                ("activity_date_end", models.DateField(blank=True, null=True)),
                ("normalized_value", models.FloatField()),
                ("normalized_unit", models.CharField(max_length=20)),
                ("ai_audit_note", models.TextField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "raw_payload",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="ingestion.rawdatapayload",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical normalized emission record",
                "verbose_name_plural": "historical normalized emission records",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
