# Generated by Django 6.0.5 on 2026-05-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalnormalizedemissionrecord",
            name="scope_category",
            field=models.CharField(
                choices=[
                    ("SCOPE_1", "Scope 1 (Direct)"),
                    ("SCOPE_2", "Scope 2 (Indirect Electricity)"),
                    ("SCOPE_3", "Scope 3 (Value Chain)"),
                ],
                default="SCOPE_1",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="normalizedemissionrecord",
            name="scope_category",
            field=models.CharField(
                choices=[
                    ("SCOPE_1", "Scope 1 (Direct)"),
                    ("SCOPE_2", "Scope 2 (Indirect Electricity)"),
                    ("SCOPE_3", "Scope 3 (Value Chain)"),
                ],
                default="SCOPE_1",
                max_length=20,
            ),
        ),
    ]
